### ISSUE TITLE
Replace wordpunct_tokenize by word_tokenize

### ISSUE THREAD

**Issue by floriancafiero** [SupervisedStylometry/SuperStyl#66] opened 2024-03-06 13:36 UTC
word_tokenize helps more complex tokenization such as mid-word punctuations. Also makes mistakes, so need to assess further, maybe not the best of ideas.

**Comment by Jean-Baptiste-Camps** [comment] 2024-03-06 15:58
Duplicate of #65

**Closed by Jean-Baptiste-Camps** 2024-03-06 15:58 UTC
